sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - ruby-head
script:
  - bundle exec rspec
matrix:
  allow_failures:
    - rvm: ruby-head
gemfile:
  - gemfiles/clockwork_master.gemfile
  - gemfiles/clockwork_1_3_1.gemfile
  - gemfiles/clockwork_2_0_0.gemfile
  - gemfiles/clockwork_2_0_1.gemfile
  - gemfiles/clockwork_2_0_2.gemfile
