sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
script:
  - bundle exec rspec
matrix:
  allow_failures:
    - rvm: ruby-head
gemfile:
  - gemfiles/clockwork_1_3_1.gemfile
  - gemfiles/clockwork_2_0_0.gemfile
  - gemfiles/clockwork_2_0_1.gemfile
  - gemfiles/clockwork_2_0_2.gemfile
